### ISSUE TITLE
Anaconda upload issues

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/ipython-sql-feedstock#1]
Running into general Anaconda upload problem described in status issue ( https://github.com/conda-forge/status/issues/4 ) with this feedstock. Please also see this upstream issue ( https://github.com/Anaconda-Platform/support/issues/60 ) for more details. See this [build](https://circleci.com/gh/conda-forge/ipython-sql-feedstock/1) for an example of this failure. Restarting to see if we can get the rest of the packages built.

**Comment by sodre** [comment]
It looks like the issue went away.
